### ISSUE TITLE
Publish to hacs

### ISSUE THREAD

**Issue by gdgib** [gdgib/span#14]
See https://github.com/hacs/default/pull/1837

In anyone else comes across this and is interested, I suppose a 👍 over there probably won't hurt.

**Comment by sargonas** [comment]
FYI this is complete now, looks like they accepted it mid October, and it now displays within HACS as expected!

**Comment by sargonas** [comment]
It appears to me that HACS has finally accepted this and now properly lists the integration within the HACS database!
