### ISSUE TITLE
Determining power returned to grid

### ISSUE THREAD

**Issue by sargonas** [gdgib/span#16]
So I'm relying on my Span's main_meter_produced to determine my solar generation, as my inverted is a Tesla Inveter_without_ a powerwall, which results in very limited data you have to collected in an even more clunky way than we do from Span (made every so less clunky thanks to you Greg!)

However I want to figure out what I am sending back to the grid, however after exploring all the entities this Integration generates, and looking over the API directly, I can't seem to find an endpoint for that. Am I correct in assuming there isn't one, and the mobile app is calculating it on the fly, and that I too will need to create some custom scripts on my side to take the produced power, subtract the consumption of the home circuits, and report out the remainder if >0 to a custom sensor I can use? Seems that is the most practical way to do it by hand but I first wanted to check to make sure that I wasn't completely missing something first?

**Comment by etmelvin** [comment]
There should be a `sensor.main_meter_produced_energy` that does what you need.

**Comment by etmelvin** [comment]
Yes, I believe that is what you have to do with the current state of the API provided to us. You should be able to do something like `max(0, main_meter_produced_power - main_meter_consumed_power)` to get the power return to grid, you’d then need to integrate that using one of the helper entity to get the total energy returned to grid.

**Comment by sargonas** [comment]
Yeah that's what I assumed, just wanted to double check I wasn't missing something obvious, thanks!
