### ISSUE TITLE
Failing during setup: async_setup_entry(

### ISSUE THREAD

**Issue by fdelacou** [gdgib/span#18]
Here is the error message in the log. It seems that all the versions that I have tried are facing that issue... :-/

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/span_panel/__init__.py:40 
Integration: Span Panel (documentation, issues) 
First occurred: 1:20:28 AM (1 occurrences) 
Last logged: 1:20:28 AM

Error setting up entry Span Panel nt-2150-c1axg for span_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/span_panel/__init__.py", line 40, in async_setup_entry
    access_token=config[CONF_ACCESS_TOKEN],
                 ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'access_token'

I"m running:
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

**Comment by altonplace** [comment]
@fdelacou I received the same error. I was able to reload the integration entry and add again by IP address. Give it a try.

**Comment by turtle2472** [comment]
I encountered this error when restoring from a backup.  I had to remove the plugin and reinstall it for it to clear and allow the connection.

**Comment by gdgib** [comment]
I'm going to leave this open, but it won't surprise me if this is no longer a problem given recent changes.  I'll try to reproduce in the next few weeks, but if anyone has further information on this after installing the recent 0.0.8 release, do chime in, please.

**Comment by gdgib** [comment]
@fdelacou @turtle2472 @altonplace any further issues with this after moving to 0.0.8?

I'm going to close this for now, but if you're still seeing these issues please just comment here and I'll happily re-open.
