### ISSUE TITLE
Future long term HACS support proposal

### ISSUE THREAD

**Issue by sargonas** [gdgib/span#24]
Hi @gdgib!

I have a proposal, if you are amenable to discussing it. I am aware from your profile bio, that coding for you is a hobby (as it is for me!) and you are much busier with your day job doing what sounds like *far* more important things. Now that your fork of the Span Panel integration has been accepted by the HACS maintainers into the core index of integrations this month, I was curious if you would be willing/interested to migrate this code base out of your personal profile into a shared organization-owned repository and share administration of that org/rep with me and any other current or future volunteers for shared maintaining? 

This way no one single individual has to feel the pressure if ensuring PRs are reviewed and releases are cut, and the expectation-workload can be shared around. (It also gives individual maintainers the ability to step back from support if life demands it, guilt free.) Given it is now natively in HACS and the Span Panels themselves are experiencing increased adoptions, I suspect this might make for the most headache free future of adoption?

**Comment by sargonas** [comment]
As there has been no response and the stale repo is causing broken compatibility for users without my fixes, I am going to to the above proposal myself, and go ahead and spin my fork out into it's on GH organization instead, and invite a few folks as co collaborators with me, so that I am not a Single Point of Failure, and petition the HACS maintainers to redirect the entry to that updated repo.

**Comment by gdgib** [comment]
I don't object to, but if you want, I'd be happy to add some maintainers here, too. I'll be catching up on the SPAN/HA issues over the weekend.

**Comment by sargonas** [comment]
Easier is always better! If you are amenable to sharing management access to other maintainers in this repo, that's the most straightforward option and also will ensure no weirdness with the HACS configurations as well.

**Comment by gdgib** [comment]
Sold.  @sargonas your collaborator invite is already sent.  I'm open to others.

I will likely spin this out into an org, along with a few other HACS add-ons I'm maintaining custom forks of, but that will take place over the coming months.

Feel free to bug me again if the current situation isn't acceptable to you.  I do apologize for the gap: we had some electrical work, which 1. ate up my time, and 2. kept me away from SPAN.  I've adjusted my email filters to avoid such heartbreak in the unlikely event we have more work that annoying in the future.

**Comment by sargonas** [comment]
All good, real life happens!

**Comment by gdgib** [comment]
I sincerely appreciate your understanding.  Looking forward to working with you.
