### ISSUE TITLE
previous durable authentication additions may have a missing step on AuthKey

### ISSUE THREAD

**Issue by sargonas** [gdgib/span#27]
I was looking to add in some automatic auth-key generation, so the user won't have to make one manually and paste it into the config flow, but looking at the code it looks like the steps to do so *are* there, at least i see code for it.

So either: 
A: the key is being generated but not used in the flow (either intentionally or unintentionally) and not getting passed into the right step, hence the need to paste one in.
or
B: the code does not work and is stubbed out but needs more work.

In any case I am going to take a look at how to get this working correctly, so that if you select "auth key" from the flow menu, the next step will generate the key in the background, and feed it into the app, and move right along smoothly. I also welcome anyone else familiar with this stuff to take a look at it with me, if they would like.

**Comment by mbbush** [comment]
Maybe you didn't notice or see https://github.com/sargonas/span/pull/7 ? I'll retarget it to this repo.

I think it's mostly a documentation issue, making it easier for the user to know what to do, and most of the heavy lifting is done. I spent some time last weekend reading through the code of this integration, and there are a few things that seem questionable as far as when new objects are getting created vs reused, and how the async is handled, that might manifest as auth failures.

**Comment by sargonas** [comment]
Yup,. I sure did. Looks like it came in while I was traveling for turkey day and flew right under my radar.

First up, thanks for the added clarity on the "actually relook at 15 minutes for real this time" timeline. Based on my own experience it doesn't seem to be re-locking that fast since the recent update, but it *is* locking much sooner than before where it could be days.

Also thanks for your PR, merging it in now. Definitely a lost context and lost documentation understanding on my part. I really appreciate the PR to help clarify that. I was poking at the code right now actually and found that post to the registration endpoint to generate the key and was literally in the middle of stepping through all the code flows to find out how and where it was (presumably) being leveraged, and what I had missed, when I got your notification on this comment. This all makes so much more sense now, and I see what I missed, thanks!
