### ISSUE TITLE
Can all of the numbers be set to 2 decimal places

### ISSUE THREAD

**Issue by Darkcitadel** [gdgib/span#30]
I got this working and its great but all of the Power numbers are things like "37.5719146728516 W".  Could they all be rounded to 2 or 3 decimal places at most.

**Comment by matellis** [comment]
You can change this for any entity in HA. Via Settings -> Devices & Services -> Entity tab, find the entity you would like to change and click on it. Click on the gear wheel in the top right, select the precision you would like from the "Display Precision" menu and then press UPDATE. Voila!

**Comment by sargonas** [comment]
I'm of the mind this should be a personal preference kind of thing, where folks are free to adjust the display values to the rounding of their choice as explained above, and leaving the raw values as precise as the Span panel reports them. This is just to ensure that folks have as much or as little data as they need for any automations or integrations they base off of this.

**Comment by gdgib** [comment]
@sargonas hit the nail on the head.  What I will do: I'll fold instructions based on the ones written up by @matellis into the README for everyone coming after.

**Comment by gdgib** [comment]
This is in the 0.0.8 release.  I also updated the suggested precision, so by default you should only see 2 decimal places, but you can configure the UI to show more or fewer as you prefer.
