### ISSUE TITLE
Areas?

### ISSUE THREAD

**Issue by matellis** [gdgib/span#31]
Is there any way to obtain Area information from the API and present it in HA? That would support some pretty helpful Sankey charts without having to manually manage the entities in two places.

**Comment by gdgib** [comment]
@matellis can you offer a little more information here?

You're asking if the span add on could somehow obtain area information from the HomeAssistant API?  I'm sure it could.

More specifically, can you clarify what duplicate entity information you're managing that would like to stop having to manage?

**Comment by gdgib** [comment]
@matellis I'm going to close this for now.  If you can provide some further information, I would be happy to re-open and address it, but as of right now, I'm sorry to say I just don't understand the request well enough to address it.
