### ISSUE TITLE
Warning of ENERGY_WATT_HOUR and POWER_WATT pending deprecation

### ISSUE THREAD

**Issue by sargonas** [gdgib/span#41]
Upon startup, HA logs trigger the following two warnings:

`ENERGY_WATT_HOUR was used from span_panel, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead`
and
`POWER_WATT was used from span_panel, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead`

I tried to find some relevant developer docs or posts about this change, but can't seem to find any just yet. This is probably a *super* recent change that supporting documentation may not be live for yet.

We have plenty of time on this one, since 2025.1 is a bit of a ways off yet, but logging this now for tracking purposes so we can start looking into making the needed changes where relevant. I'll try to take a stab at the switch myself here in the coming days once I return from some travels.

**Comment by cayossarian** [comment]
I made that change once in my own code before I took it out to work on [https://github.com/gdgib/span/pull/40](https://github.com/gdgib/span/pull/40l).  The change for deprecated power/energy units is not big but it will affect the same sensor files as are in the solar inverter pull request.  I could layer a commit on top of that if it's helpful.

**Comment by sargonas** [comment]
If you're already familiar with it that would be super helpful to add, plus sounds like this way it will stay forward compatible.

**Comment by cayossarian** [comment]
Sure, the commit to address this issue is in the feature branch in [https://github.com/gdgib/span/pull/40](https://github.com/gdgib/span/pull/40l)
