### ISSUE TITLE
Integration requires reconfiguration w/ Auth Key

### ISSUE THREAD

**Issue by pavandave** [gdgib/span#49]
When using AuthKey on initial startup, after 6ish-12 hours (sometimes longer) the integration stops and requires reconfiguration. It then prompts me to open the door when I click on it.

![image](https://github.com/gdgib/span/assets/45403213/ff4dffe3-27c8-4ed8-b399-5a89e663cc92)

In integrations page I see that there is a device requiring reconfiguration:

![image](https://github.com/gdgib/span/assets/45403213/5a8f5b23-1866-4cbf-9f40-53bcd023b32a)

When I remove that device and then re-add the device via Auth token, using the last auth token I generated, I am able to successfully connect:
![image](https://github.com/gdgib/span/assets/45403213/48ad1246-15cb-4eef-a677-1114d0a2dbb2)

Not sure if this is expected or a bug in the re-auth logic? Just deleting the panel and re-entering the prior authkey fixes this.

**Comment by cayossarian** [comment]
There was a bug that was fixed, are you on the latest version?   What should s in the log relative to the integration?

**Comment by pavandave** [comment]
I redownload and am on 0.0.8. 

I enabled debugging for next time it happens.

**Comment by cayossarian** [comment]
@pavandave I looked at the source for 0.0.8 and the fix is not in that release.  The original issues was #29 and did not make the 0.0.8 release.  I'm not the repository owner although I push the fix here so I can't really create a release here.

In the meantime you can use a custom repository that does have the fix and perhaps some others.  No need to run in debug.
Use this repository as a custom repository and you should be good to go.  https://github.com/cayossarian/span

**Comment by pavandave** [comment]
@cayossarian  No issues for a few days after implementing your fix. Will close this comment as duplicate of #29. Thanks!

**Comment by joergbattermann** [comment]
> @pavandave I looked at the source for the 0.0.8 release zip and the fix is not in that release. The original issues was #29 and did not make the 0.0.8 release. I'm not the repository owner although I pushed the fix here from my repository so I can't really create a release here.
> 
> In the meantime you can use a custom repository that does have the fix and perhaps some others. No need to run in debug. Uninstall your current span integration and use the following repository as a custom repository and you should be good to go. https://github.com/cayossarian/span

I had the same issue and switched over to the repo by @cayossarian etc.. seemingly fixed it for us as well. Thanks!!
