### ISSUE TITLE
Circuit Priority

### ISSUE THREAD

**Issue by nalditopr** [gdgib/span#53]
I'm unable to update circuit priorities using homeassistant. Getting an http 500 server error and happening on all breakers. Everything else works and I'm able to toggle breakers on and off.

Span panel version spanos2/r202441/04

**Comment by sargonas** [comment]
This is a known issue. Since day one the API on the SPAN side has not worked properly with those commands… Given the API is unofficial and undocumented, we've been warned by one of the SPAN engineers that functionality like that is a little crunchy around the edges at this time.

**Comment by nalditopr** [comment]
Thank you for the clarification. Hopefully they invest into the API more.
